import { strict as assert } from 'node:assert';
import { createServer } from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import { resolve, extname } from 'node:path';
import { chromium } from '@playwright/test';

const root = resolve('dist-h5');
const mime = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png' };
const server = createServer(async (req, res) => {
  try {
    const path = resolve(root, `.${new URL(req.url, 'http://localhost').pathname === '/' ? '/index.html' : new URL(req.url, 'http://localhost').pathname}`);
    assert(path.startsWith(`${root}/`));
    const body = await readFile(path); res.writeHead(200, { 'Content-Type': mime[extname(path)] || 'application/octet-stream' }); res.end(body);
  } catch { res.writeHead(404); res.end('Not found'); }
});
await new Promise(done => server.listen(0, '127.0.0.1', done));
const port = server.address().port;
let browser;
try {
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH ? { executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH } : {}) });
  const page = await browser.newPage({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const screen = () => page.locator('.taro_page_show:not(.taro_page_shade)').last();
  const click = async text => { await screen().getByText(text, { exact: true }).click(); await page.waitForTimeout(450); };
  const input = placeholder => screen().locator(`input[placeholder="${placeholder}"]`);
  const snapshot = async () => page.evaluate(() => {
    const raw = localStorage.getItem('jiqian_demo_v1');
    const value = raw ? JSON.parse(raw) : null;
    return Array.isArray(value) ? value : value?.data;
  });
  await page.goto(`http://127.0.0.1:${port}`);
  await screen().getByText('去川西，找个秋天', { exact: true }).waitFor();
  await mkdir('artifacts', { recursive: true });
  await page.screenshot({ path: 'artifacts/trips.png', fullPage: true });
  await click('去川西，找个秋天');
  await screen().getByText('¥658.00', { exact: true }).waitFor();
  await page.screenshot({ path: 'artifacts/overview.png', fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 390, '移动端页面不能横向溢出');
  await page.evaluate(() => localStorage.setItem('jiqian_draft_demo_trip_demo_me_new', JSON.stringify({ data: { amount: '10.5雅江', title: '旧缓存内容' } })));
  await click('＋ 记一笔共同开销');
  assert.equal(await input('0.00').inputValue(), '', '旧版草稿不能恢复到新表单');
  await input('0.00').fill('10.01');
  await input('比如：康定住宿、午饭、加油').fill('路边的热咖啡');
  await screen().locator('.participant-row').filter({ hasText: '阿宇' }).click();
  await page.waitForTimeout(100);
  await click('返回账单');
  await click('＋ 记一笔');
  assert.equal(await input('0.00').inputValue(), '', '离开后新增表单必须为空');
  assert.equal(await input('比如：康定住宿、午饭、加油').inputValue(), '');
  await input('0.00').fill('20.00');
  await page.reload(); await page.waitForTimeout(650);
  assert.equal(await input('0.00').inputValue(), '', '重新加载不能恢复未提交金额');
  await input('0.00').fill('10.01');
  await input('比如：康定住宿、午饭、加油').fill('路边的热咖啡');
  await screen().locator('.participant-row').filter({ hasText: '阿宇' }).click();
  await click('保存这笔开销');
  await screen().getByText('路边的热咖啡', { exact: true }).waitFor();
  let trips = await snapshot();
  const bill = trips[0].expenses.find(e => e.title === '路边的热咖啡');
  assert.equal(bill.amount, 1001); assert.equal(bill.participantIds.length, 3);
  assert.equal(Object.values(bill.shares).reduce((a, b) => a + b, 0), 1001);
  await click('路边的热咖啡');
  await input('0.00').fill('12.01'); await click('保存修改');
  trips = await snapshot(); assert.equal(trips[0].expenses.find(e => e.id === bill.id).amount, 1201);
  // 编辑过程中其他成员改名，仍应保存；同一笔账单被改动则保留当前页输入并要求核对。
  await click('路边的热咖啡');
  await input('0.00').fill('714.00');
  await input('比如：康定住宿、午饭、加油').fill('香格里拉镇酒店');
  await page.evaluate(() => {
    const raw = JSON.parse(localStorage.getItem('jiqian_demo_v1'));
    const trips = Array.isArray(raw) ? raw : raw.data;
    trips[0].members[3].name = '糖糖的新昵称'; trips[0].version++;
    localStorage.setItem('jiqian_demo_v1', JSON.stringify(raw));
  });
  await click('保存修改');
  await screen().getByText('香格里拉镇酒店', { exact: true }).waitFor();
  await screen().getByText('已保存到共享账本，下方已显示最新账单。', { exact: true }).waitFor();
  assert.equal(await screen().locator('.expense-row').filter({ hasText: '香格里拉镇酒店' }).locator('.amount').textContent(), '¥714.00');
  await click('香格里拉镇酒店');
  await input('0.00').fill('700.00');
  await page.evaluate(id => {
    const raw = JSON.parse(localStorage.getItem('jiqian_demo_v1'));
    const trips = Array.isArray(raw) ? raw : raw.data;
    const expense = trips[0].expenses.find(e => e.id === id);
    expense.amount = 80000; expense.updatedAt++; trips[0].version++;
    localStorage.setItem('jiqian_demo_v1', JSON.stringify(raw));
  }, bill.id);
  await click('保存修改');
  await screen().getByText('核对最新账单', { exact: true }).waitFor();
  assert.match(await screen().locator('.error-banner').textContent(), /未保存/);
  assert.equal(await input('0.00').inputValue(), '700.00');
  assert.equal(await screen().getByText('保存修改', { exact: true }).evaluate(el => el.disabled), true);
  trips = await snapshot(); assert.equal(trips[0].expenses.find(e => e.id === bill.id).amount, 80000, '冲突不能覆盖朋友的修改');
  await click('核对最新账单');
  const comparison = await page.locator('.taro-modal__text').textContent();
  assert.match(comparison, /800.00/); assert.match(comparison, /700.00/);
  await page.locator('.taro-model__confirm').click(); await page.waitForTimeout(250);
  await click('保存修改');
  await screen().getByText('香格里拉镇酒店', { exact: true }).waitFor();
  assert.equal(await screen().locator('.expense-row').filter({ hasText: '香格里拉镇酒店' }).locator('.amount').textContent(), '¥700.00');
  await page.reload(); await page.waitForTimeout(650);
  assert.equal(await screen().locator('.expense-row').filter({ hasText: '香格里拉镇酒店' }).locator('.amount').textContent(), '¥700.00');
  await click('香格里拉镇酒店');
  await input('0.00').fill('999.00');
  await click('返回账单'); await click('香格里拉镇酒店');
  assert.equal(await input('0.00').inputValue(), '700.00', '重开编辑页必须读取已保存金额');
  await input('0.00').fill('888.00');
  await page.reload(); await page.waitForTimeout(650);
  assert.equal(await input('0.00').inputValue(), '700.00', '刷新编辑页不能恢复未提交修改');
  assert.deepEqual(await page.evaluate(() => Object.keys(localStorage).filter(k => k.startsWith('jiqian_draft_'))), ['jiqian_draft_demo_trip_demo_me_new'], '不得创建新草稿缓存');
  await click('删除账单');
  await page.locator('.taro-model__confirm').click(); await page.waitForTimeout(450);
  trips = await snapshot(); assert.equal(trips[0].expenses.find(e => e.id === bill.id).deleted, true);
  await click('旅伴');
  await screen().locator('.member-row').filter({ hasText: '小林' }).getByText('切换身份', { exact: true }).click();
  await page.waitForTimeout(250); await click('结算');
  await click('我已转账，通知对方确认');
  await page.locator('.taro-model__confirm').click(); await page.waitForTimeout(450);
  trips = await snapshot(); assert.equal(trips[0].settlements[0].status, 'pending');
  await click('旅伴');
  await screen().locator('.member-row').filter({ hasText: '创建者' }).getByText('切换身份', { exact: true }).click();
  await page.waitForTimeout(250); await click('结算');
  await click('确认到账'); await page.locator('.taro-model__confirm').click(); await page.waitForTimeout(450);
  trips = await snapshot(); assert.equal(trips[0].settlements[0].status, 'confirmed');
  await page.screenshot({ path: 'artifacts/settlement.png', fullPage: true });
  await page.reload(); await page.waitForTimeout(650);
  trips = await snapshot(); assert.equal(trips[0].settlements[0].status, 'confirmed', '刷新后数据应保留');
  await page.goto(`http://127.0.0.1:${port}/#/pages/trips/index`); await page.waitForTimeout(500);
  await click('＋ 创建旅行');
  await input('比如：川西七日，去看秋天').fill('下一站，四姑娘山');
  await screen().locator('.modal-sheet').getByText('创建旅行', { exact: true }).click(); await page.waitForTimeout(500);
  await screen().getByText('下一站，四姑娘山', { exact: true }).waitFor();
  trips = await snapshot(); assert.equal(trips.length, 2);
  // 模拟首次打开邀请的新成员：默认“旅友”不再作为已填写的名字。
  await page.evaluate(() => {
    const raw = JSON.parse(localStorage.getItem('jiqian_demo_user_v1'));
    const user = { id: 'new_guest', name: '旅友' };
    localStorage.setItem('jiqian_demo_user_v1', JSON.stringify(raw && 'data' in raw ? { ...raw, data: user } : user));
  });
  await page.goto(`http://127.0.0.1:${port}/#/pages/trips/index?invite=chuanxi2026`);
  await page.reload();
  await screen().locator('.modal-sheet').waitFor();
  assert.equal(await input('填写朋友认识的名字').inputValue(), '', '新成员不能默认使用旅友');
  assert.equal(await input('粘贴朋友分享的邀请码').inputValue(), 'chuanxi2026');
  const joinButton = screen().locator('.modal-sheet .button-primary').filter({ hasText: /^加入旅行$/ });
  assert.equal(await joinButton.evaluate(el => el.disabled), true);
  await input('填写朋友认识的名字').fill('张同学');
  await joinButton.click(); await page.waitForTimeout(500);
  await screen().locator('.trip-name-value').filter({ hasText: '张同学' }).waitFor();
  trips = await snapshot();
  const joinedTrip = trips.find(t => t.inviteCode === 'chuanxi2026');
  const previousExpenses = joinedTrip.expenses;
  assert.equal(joinedTrip.members.find(m => m.id === 'new_guest').name, '张同学');
  await click('修改名字');
  await input('填写朋友认识的名字').fill('');
  assert.equal(await screen().locator('.modal-sheet .button-primary').filter({ hasText: /^保存名字$/ }).evaluate(el => el.disabled), true);
  await input('填写朋友认识的名字').fill('小张');
  await click('保存名字');
  await screen().locator('.trip-name-value').filter({ hasText: '小张' }).waitFor();
  await click('旅伴');
  await screen().locator('.member-row').filter({ hasText: '小张' }).waitFor();
  await page.screenshot({ path: 'artifacts/member-name.png', fullPage: true });
  trips = await snapshot();
  assert.deepEqual(trips.find(t => t.id === joinedTrip.id).expenses, previousExpenses, '改名不改变历史账单');
  await click('修改名字');
  await input('填写朋友认识的名字').fill('不保存的名字'); await click('取消');
  assert.equal(await screen().locator('.trip-name-value').textContent(), '小张');
  await page.reload(); await page.waitForTimeout(650);
  assert.equal(await screen().locator('.trip-name-value').textContent(), '小张', '刷新后旅行昵称保留');
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth), 390);
  assert.deepEqual(errors, [], '浏览器不得出现运行时错误');
  console.log('H5 验证通过：创建旅行、部分人分摊、离开及刷新不保留未提交输入、修改删除、转账确认、刷新持久化、改名期间保存、同笔冲突核对和离开及刷新不保留未提交输入、邀请填写姓名、旅行内改名及取消、移动端布局。');
} finally {
  await browser?.close(); await new Promise(done => server.close(done));
}
